Risk manager:
Initial balance: 10000
Stop losses: [2]
Risk/Reward ratios: [1.5]
Trade risk: 100.0
Action space: 4
{0: Action(long, sl: 2, rr: 1.5),
 1: Action(short, sl: 2, rr: 1.5),
 2: Action(hold, sl: None, rr: None),
 3: Action(close, sl: None, rr: None)}
None
Choose action:         action_type
0  long_sl:2_rr:1.5)
Choose action:         action_type
0  long_sl:2_rr:1.5)
1  long_sl:2_rr:1.5)
Choose action:          action_type
0   long_sl:2_rr:1.5)
1   long_sl:2_rr:1.5)
2  short_sl:2_rr:1.5)
Choose action:             action_type
0      long_sl:2_rr:1.5)
1      long_sl:2_rr:1.5)
2     short_sl:2_rr:1.5)
3  hold_sl:None_rr:None)
Choose action:              action_type
0       long_sl:2_rr:1.5)
1       long_sl:2_rr:1.5)
2      short_sl:2_rr:1.5)
3   hold_sl:None_rr:None)
4  close_sl:None_rr:None)
Choose action:
Traceback (most recent call last):
  File "/Users/milosz/Documents/Pycharm/InanceAlgo/main_debug.py", line 59, in <module>
    env.step(action=action)
  File "/Users/milosz/Documents/Pycharm/InanceAlgo/env.py", line 73, in step
    self.risk_manager.execute_action(action_index=int(action),
  File "/Users/milosz/Documents/Pycharm/InanceAlgo/risk_manager.py", line 86, in execute_action
    action = self.action_dict[action_index]
KeyError: 4