Traceback (most recent call last):
  File "/Users/milosz/Documents/Pycharm/InanceAlgo/main_test_agent.py", line 65, in <module>
    observation_, reward, _, done, info = env.step(action)
  File "/Users/milosz/Documents/Pycharm/InanceAlgo/env.py", line 87, in step
    table = wandb.Table(data=self.risk_manager.action_history,
  File "/Users/milosz/opt/anaconda3/envs/Inance/lib/python3.10/site-packages/wandb/data_types.py", line 288, in __init__
    self._init_from_list(data, columns, optional, dtype)
  File "/Users/milosz/opt/anaconda3/envs/Inance/lib/python3.10/site-packages/wandb/data_types.py", line 307, in _init_from_list
    assert type(data) is list, "data argument expects a `list` object"
AssertionError: data argument expects a `list` object