2023-04-26 09:20:33,436 INFO    MainThread:60631 [wandb_setup.py:_flush():76] Configure stats pid to 60631
2023-04-26 09:20:33,436 INFO    MainThread:60631 [wandb_setup.py:_flush():76] Loading settings from /Users/milosz/.config/wandb/settings
2023-04-26 09:20:33,436 INFO    MainThread:60631 [wandb_setup.py:_flush():76] Loading settings from /Users/milosz/Documents/Pycharm/InanceAlgo/test_agent/wandb/settings
2023-04-26 09:20:33,436 INFO    MainThread:60631 [wandb_setup.py:_flush():76] Loading settings from environment variables: {}
2023-04-26 09:20:33,436 INFO    MainThread:60631 [wandb_setup.py:_flush():76] Applying setup settings: {'_disable_service': False}
2023-04-26 09:20:33,436 INFO    MainThread:60631 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program_relpath': 'main_test_agent.py', 'program': '/Users/milosz/Documents/Pycharm/InanceAlgo/main_test_agent.py'}
2023-04-26 09:20:33,437 INFO    MainThread:60631 [wandb_init.py:_log_setup():507] Logging user logs to /Users/milosz/Documents/Pycharm/InanceAlgo/test_agent/wandb/run-20230426_092033-0h2s94n3/logs/debug.log
2023-04-26 09:20:33,437 INFO    MainThread:60631 [wandb_init.py:_log_setup():508] Logging internal logs to /Users/milosz/Documents/Pycharm/InanceAlgo/test_agent/wandb/run-20230426_092033-0h2s94n3/logs/debug-internal.log
2023-04-26 09:20:33,437 INFO    MainThread:60631 [wandb_init.py:init():547] calling init triggers
2023-04-26 09:20:33,437 INFO    MainThread:60631 [wandb_init.py:init():554] wandb.init called with sweep_config: {}
config: {}
2023-04-26 09:20:33,437 INFO    MainThread:60631 [wandb_init.py:init():590] wandb.init() called when a run is still active
2023-04-26 09:20:33,437 INFO    MainThread:60631 [wandb_config.py:__setitem__():152] config set log_interval = 250 - <bound method Run._config_callback of <wandb.sdk.wandb_run.Run object at 0x7f7e70f5e9e0>>
2023-04-26 09:20:33,437 INFO    MainThread:60631 [wandb_run.py:_config_callback():1285] config_cb log_interval 250 None
2023-04-26 09:20:41,983 WARNING MsgRouterThr:60631 [router.py:message_loop():77] message_loop has been closed
