Traceback (most recent call last):
  File "/Users/milosz/Documents/Pycharm/InanceAlgo/main_test_agent.py", line 65, in <module>
    observation_, reward, _, done, info = env.step(action)
  File "/Users/milosz/Documents/Pycharm/InanceAlgo/env.py", line 92, in step
    table = wandb.Table(data=[[self.current_step + i] for i in range(5)],
  File "/Users/milosz/opt/anaconda3/envs/Inance/lib/python3.10/site-packages/wandb/data_types.py", line 288, in __init__
    self._init_from_list(data, columns, optional, dtype)
  File "/Users/milosz/opt/anaconda3/envs/Inance/lib/python3.10/site-packages/wandb/data_types.py", line 309, in _init_from_list
    self._assert_valid_columns(columns)
  File "/Users/milosz/opt/anaconda3/envs/Inance/lib/python3.10/site-packages/wandb/data_types.py", line 301, in _assert_valid_columns
    assert type(columns) is list, "columns argument expects a `list` object"
AssertionError: columns argument expects a `list` object